# Afin de definir un type complexe on utilise le mot clé "type"
# Celui-ci est interprété par le serveur GraphQL
# Ce type sera alors accessible dans l'ensemble du schema en tant que nouveau type.
"Une catégorie de film"
type Category {
    id: PositiveInt!
    label: String!
    created_at: DateTime!
    updated_at: DateTime
    movies: [Movie!]!
}
